config/routes.rb
EpicsBdeTool::Application.routes.draw do

  get "stock_details/edit_current_quantity"
  post "stock_details/board_off_stock"
  get "stock_details/edit_stock_details"
  post "stock_details/save_edited_stock_details"
  post "stock_details/void"
  get "stock_details/void_transaction"

  get "product/search"
  get "product/select"
  get "product/find_by_name_or_code"
  get "product/data_entry"
  post "product/data_entry"
  post "product/save_transaction"
  get "product/stock_card"
  post "product/stock_card"
  get "product/view"
  post "product/view"


  get "home/index"

  ######## person #########

  get "person/add_person"
  post "person/new_person"
  get "person/get_name"

  ######## person #########

  ######## user ########
  match '/login' => "user#login"
  match '/logout' => "user#logout"
  post "user/authenticate"
  get "user/enter_workstation"
  post "user/locations"
  get "/user/new"
  post "user/create"
  get "user/summary"
  get "user/edit"
  get "user/change_password"
  post "user/change_password"
  get "user/change_username"
  post "user/change_username"
  get "user/change_user_role"
  post "user/change_user_role"
  get "user/void"
  ######## user end ########


  ######### location_type start ########
  get "location_type/index"
  get "location_type/new"
  post "location_type/create"
  get "location_type/edit"
  post "location_type/update"
  get "location_type/void"
  ######### location_type end ########

  ######## location start ###########
  get "location/index"
  get "location/new"
  post "location/create"
  get "location/edit"
  post "location/update"
  get "location/void"
  get "location/search"
  get "location/print_location_menu"
  post "location/print_location"
  get "location/location_label"
  ######## location end #######


  ########### reports start #########
  get "report/drug_availability"
  get "report/drug_availability_printable"
  post "report/drug_availability_printable"
  post "report/daily_dispensation"
  post "report/daily_dispensation_printable"
  get "report/store_room"
  post "report/store_room_printable"
  get "report/view_alerts"
  get "report/select_store"
  match 'alerts/:name' => 'report#alerts', :as => :alerts
  get "report/select_date_range"
  post "report/monthly_report"
  post "report/print_monthly_report"
  get "report/monthly_report_printable"
  post "report/monthly_report_printable"
  get "report/select_daily_dispensation_date"
  match 'drug_daily_dispensation/:id/:date' => 'report#drug_daily_dispensation', :as => :drug_daily_dispensation
  get "report/expired_items"
  get "report/select_date_ranges"
  post "report/disposed_items"
  post "report/print_drug_availability_report"
  post "report/print_store_room_report"
  get "report/store_room_printable"
  post "report/print_daily_dispensation_report"
  get "report/daily_dispensation_printable"
  get 'report/missing_items'
  post 'report/print_disposed_items_report'
  get 'report/disposed_items_printable'
  post "report/audit"
  post "report/received_items"
  post "report/print_expired_items_report"
  get "report/expired_items_printable"
  get "report/items_to_expire_next_six_months_attachment"
  post "report/items_to_expire_next_six_months_attachment"
  get "report/items_to_expire_next_six_months_to_pdf"
  post "report/items_to_expire_next_six_months_to_pdf"
  get "report/daily_dispensation_attachment"
  post "report/daily_dispensation_attachment"
  get "report/daily_dispensation_to_pdf"
  post "report/daily_dispensation_to_pdf"
  get "report/received_items_attachment"
  post "report/received_items_attachment"
  get "report/received_items_to_pdf"
  post "report/received_items_to_pdf"
  get "report/monthly_report_attachment"
  get "report/monthly_report_to_pdf"
  ########### reports end #########

  root :to => 'home#index'
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  def search
    render :layout => "touch_screen"
  end

  def select
    @action = params[:task] rescue "data entry"
    render :layout => "touch_screen"
  end

  def data_entry

    types = ['facility', 'Store room', 'Departments']
    facility_id = EpicsLocationType.find_by_name("facility").id
    location_type = EpicsLocationType.where("name in (?)", types).collect{|c| c.id}
    @receivers = EpicsLocation.where("epics_location_type_id in (?)",location_type).collect{|x| x.name}
    @facilities = EpicsLocation.where("epics_location_type_id = ?",facility_id).collect{|x| x.name}
    @receivers.delete(session[:location_name])
    @suppliers = EpicsSupplier.all.collect{|x| x.name}
    @product = EpicsProduct.find_by_name(params[:product])

  end

  def save_transaction

    created_at = "#{params[:record]['date'].to_date} #{Time.now.strftime('%H:%M:%S')}" rescue nil
    product = EpicsProduct.find_by_product_code(params[:record]['item'])

    if (params[:record]['isReceipt'].downcase == "true")

      supplier =  (params[:record]['transaction'] != "receipt") ? "Other" : params[:record]['interactor']

      EpicsStock.transaction do
        stock = EpicsStock.new()
        stock.grn_date = params[:record]['date']
        stock.invoice_number = params[:record]['voucher']
        stock.epics_supplier_id = EpicsSupplier.find_by_name(supplier).id
        stock.save!

        witness = EpicsWitnessNames.new
        witness.epics_stock_id = stock.epics_stock_id
        witness.name = "Administrator"
        witness.save!

        stock_detail = EpicsStockDetails.new()
        stock_detail.epics_stock_id = stock.epics_stock_id
        stock_detail.epics_products_id = product.id
        stock_detail.epics_location_id = session[:location_id]
        stock_detail.received_quantity = params[:record]['received']
        stock_detail.current_quantity = params[:record]['received']
        stock_detail.batch_number = params[:record]['batch']
        stock_detail.epics_product_units_id = product.epics_product_units_id
        stock_detail.save!

        stock_expiry_dates = EpicsStockExpiryDates.new()
        stock_expiry_dates.epics_stock_details_id = stock_detail.epics_stock_details_id
        stock_expiry_dates.expiry_date = params[:record]['date'].to_date + 1.year
        stock_expiry_dates.save!

      end

      result = "Record Saved Successfully"

    else

      stock = EpicsStockDetails.find(:first,:conditions =>["batch_number = ? and current_quantity >= ? and epics_products_id = ?",
                                                           params[:record]['batch'],params[:record]['issued'],product.id ])

      if (stock.blank?)
        result = "Insufficient quantity to issue"
      else

        order_type = EpicsOrderTypes.find_by_name(params[:record]["transaction"])

        EpicsOrders.transaction do
          order = EpicsOrders.new()
          order.epics_order_type_id = order_type.id
          order.epics_location_id = EpicsLocation.find_by_name(params[:record]['interactor']).id
          order.created_at = created_at
          order.save

          item_order = EpicsProductOrders.new()
          item_order.epics_order_id = order.id
          item_order.epics_stock_details_id = stock.id
          item_order.quantity = params[:record]['issued']
          item_order.created_at = "#{order.created_at.to_date} #{Time.now.strftime('%H:%M:%S')}"
          item_order.save

          stock.current_quantity = (stock.current_quantity - params[:record]['issued'].to_i)
          stock.save
        end

        result = "Record Saved Successfully"
      end

    end

    render :text => result
  end

  def find_by_name_or_code
    @products = EpicsProduct.where("(product_code LIKE(?) OR
      name LIKE (?))", "%#{params[:search_str]}%",
                                   "%#{params[:search_str]}%").limit(100).map{|product|[[product.name]]}

    render :text => "<li></li><li>" + @products.join("</li><li>") + "</li>"
  end
  def view
    @product = EpicsProduct.where("name = ?",params[:product])[0]
    if @product.blank?
      redirect_to "/"
    else
      session[:product] = params[:product]
      render :layout => "custom"
    end
  end
  def stock_card
    @item = EpicsProduct.find_by_name(params[:product])
    @page_title = "#{@item.name}<br />Stock Card"
    @trail = {}

    EpicsReport.receipts(@item, @trail)
    EpicsReport.issues(@item, @trail)
    EpicsReport.negative_adjustments(@item, @trail)
    EpicsReport.positive_adjustments(@item, @trail)
    EpicsReport.losses(@item, @trail)

  end
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/product/search.html.erb
<script>
    tt_cancel_show='/'
    tt_cancel_destination='/'

    function set_ajaxURL_for_suggestions() {
    url = "/product/find_by_name_or_code?search_str=";
    $('touchscreenInput'+tstCurrentPage).setAttribute('ajaxURL', url);
    listSuggestions(tstCurrentPage);
  }

</script>

<% form_tag "view", :method => :post do %>
  <%= text_field_tag :product, nil, 
    {:field_type => 'alpha', 
     :helpText => 'Enter item name/item code to find',
     :tt_onLoad => 'set_ajaxURL_for_suggestions();',
     :ajaxURL => '' 
    }
  %>

  <%= submit_tag "Find product" %>
<% end %>

app/views/product/select.html.erb
<script>
    tt_cancel_show='/'
    tt_cancel_destination='/'

    function set_ajaxURL_for_suggestions() {
    url = "/product/find_by_name_or_code?search_str=";
    $('touchscreenInput'+tstCurrentPage).setAttribute('ajaxURL', url);
    listSuggestions(tstCurrentPage);
  }

</script>

<% form_tag @action, :method => :post do %>
  <%= text_field_tag :product, nil, 
    {:field_type => 'alpha', 
     :helpText => 'Enter item name/item code to find',
     :tt_onLoad => 'set_ajaxURL_for_suggestions();',
     :ajaxURL => '' 
    }
  %>

  <%= submit_tag "Find product" %>
<% end %>

app/views/product/stock_card.html.erb
<html>
  <head>
    <script>
      function addPrinterIcon(){
        nav = document.getElementById('nav')
        img = document.createElement('img')
        img.src="/images/emblem_print.png"
        img.id='printer'
        img.onclick=function(){
          printStockCard();
        }
        nav.appendChild(img)
      }
      // window.setTimeout("addPrinterIcon();", 50)

      function printStockCard(){

        jQuery.ajax({
          type: "POST",
          url: "/product/print_stock_card",
          data: "id=<%=  params[:id] %>",
          success: function(){
            
          }

        });
      }

      function confirm(transaction_id, name) {
          document.getElementById('shadow').style.display = 'block';
          document.getElementById('question').style.display = 'block';
          document.getElementById('yes').setAttribute("onmousedown", "voidTransaction("+transaction_id+",'" + name +"')" );
      }
      function hide(){
          document.getElementById('shadow').style.display = 'none';
          document.getElementById('question').style.display = 'none';
      }
      function voidTransaction(transaction_id, name) {
        var product_id = <%=@item.id%>;

        if (window.XMLHttpRequest) {// code for IE7+, Firefox, Chrome, Opera, Safari  
          xmlhttp=new XMLHttpRequest();                                             
        }else{// code for IE6, IE5                                                  
          xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");                           
        }                                                                           
        xmlhttp.onreadystatechange=function() {                                     
          if (xmlhttp.readyState==4 && xmlhttp.status==200) {                       
            var results = xmlhttp.responseText;                                     
            if(results == 'undefined' || results == '' || results == '"not validate"') {                           
              return;                                                               
            }else{                                                                  
              hide();
              location.reload();
            }                                                                       
          }                                                                         
        }                                                   

        url = "/stock_details/void_transaction?transaction_id=";
        url += transaction_id + "&transaction=" + name + "&product_id=" + product_id;
        xmlhttp.open("GET", url, true);
        xmlhttp.send();

      }

    </script>

    <style>
     #printer{
        height: 65px;
        margin-left: 75%;
        cursor: pointer;
        float: left;
      }
     .tbody-header tr, td {
     /*   border-right: solid 1px black; 
        border-bottom: solid 1px black;
        border-left: solid 1px black;
        border-top: solid 1px black; */
        padding-left: 10px;
      }

      .stock_card {
        width: 100%;                                                                  
        border-collapse: collapse;                                                    
        margin-top: 10px;
      }

      .tbody-header td {
        border-style: solid;
        border-width: 1px;
        font-weight:bold;
      }

      .tbody-data td {
        border-style: solid;
        border-width: 1px;
      }

      .row_blue td {
        background-color: lightgrey;
      }

      .void-buttons {
        width: 75px;
        height: 75px;
      }
     #shadow, #question {
         -moz-user-select: none;
     }

     div {
         -moz-user-select: none;
     }
      div.confirmation{
          background-color: #FF6347;
          border: 2px solid #000000;
          height: 25%;
          left: 35%;
          padding: 10px;
          position: absolute;
          text-align: center;
          top: 20%;
          display: none;
          vertical-align: middle;
          width: 30%;
          z-index: 1001;
          font-size: 35px;
      }
     button.btn {
         -moz-box-shadow:inset 0px 1px 0px 0px #bbdaf7;
         -webkit-box-shadow:inset 0px 1px 0px 0px #bbdaf7;
         box-shadow:inset 0px 1px 0px 0px #bbdaf7;
         background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #79bbff), color-stop(1, #378de5) );
         background:-moz-linear-gradient( center top, #79bbff 5%, #378de5 100% );
         filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#79bbff', endColorstr='#378de5');
         background-color:#79bbff;
         -moz-border-radius:42px;
         -webkit-border-radius:42px;
         border-radius:42px;
         border:1px solid #84bbf3;
         display:inline-block;
         color:#ffffff;
         font-family:arial;
         font-size:30px;
         font-weight:bold;
         padding:6px 24px;
         text-decoration:none;
         text-shadow:1px 1px 0px #528ecc;
         width: 120px;
         text-align: center;
     }.btn:hover {
          background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #378de5), color-stop(1, #79bbff) );
          background:-moz-linear-gradient( center top, #378de5 5%, #79bbff 100% );
          filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#378de5', endColorstr='#79bbff');
          background-color:#378de5;
      }.btn:active {
           position:relative;
           top:1px;
       }
    </style>

  </head>
  <body>
   <div style="overflow:auto; height:590px">
    <table class="stock_card">
      <thead>
        <tr class="tbody-header">
          <td style="padding-left: 10px;">Product name</td>
          <td style="padding-left: 10px;font-weight: normal;"><%=@item.name%></td>
          <%if User.current.epics_user_role.name == "Administrator"%>
            <td colspan="68"></td>
          <%else%>
            <td colspan="67"></td>
          <%end%>
        </tr>
        <tr class="tbody-header">
          <td>CODE</td>
          <td style="padding-left: 10px;font-weight: normal;"><%=@item.product_code%></td>
          <td>Unit of issue</td>
          <%if User.current.epics_user_role.name == "Administrator"%>
            <td colspan="7" style="padding-left: 10px;font-weight: normal;"><%=@item.epics_product_units.name%></td>
          <%else%>
            <td colspan="6" style="padding-left: 10px;font-weight: normal;"><%=@item.epics_product_units.name%></td>
          <%end%>
        </tr>
        <tr class="tbody-header">
          <td>DATE<br />(A)</td>
          <td>Voucher To/From<br />(B)</td>
          <td>Quantity Received<br />(C)</td>
          <td>Quantity Issued<br />(D)</td>
          <td>Losses<br />(E)</td>
          <td>+Adjust<br />(F)</td>
          <td>-Adjust<br />(G)</td>
          <td>Quantity on Hand<br />(H)</td>
          <td>Remarks<br />(I)</td>
          <%if User.current.epics_user_role.name == "Administrator"%>
            <td>&nbsp;</td>
          <%end%>
        </tr>
      </thead>
      <tbody>

      <tr class="tbody-data">
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <%if User.current.epics_user_role.name == "Administrator"%>
          <td>&nbsp;</td>
        <%end%>
      </tr>

      <%
      color = 'white'
      total_positives = 0
      total_negatives = 0
      (@trail || {}).sort_by {|x , y| x.to_time }.each do |date , attributes| 
          (attributes).each do |invoice_number , values|
            (values).each do |batch_number , data|
              (data).each do |remark , d|
                if color == 'white'
                  color = 'blue'
                else
                  color = 'white'
                end
                    
                total_positives += d[:received_quantity].to_f if d[:received_quantity]
                total_positives += d[:quantity_received].to_f if d[:quantity_received]

                total_negatives += d[:issued].to_f if d[:issued]
                total_negatives += d[:losses].to_f if d[:losses]
                total_negatives += d[:quantity_given_out].to_f if d[:quantity_given_out]

                current_quantity = (total_positives - total_negatives)

                if(current_quantity.to_s[-2..-1] == '.0')
                  current_quantity = current_quantity.to_i
                end

                transaction = d[:transaction].upcase
                if transaction == 'BOARD OFF'
                  transaction_id = d[:epics_product_order_id]
                elsif transaction.match(/POSITIVE_ADJUSTMENTS:EXCHANGE/i)
                  transaction_id = d[:epics_exchange_id]
                elsif transaction.match(/POSITIVE_ADJUSTMENTS:BORROW/i)
                  transaction_id = d[:epics_lends_or_borrows_id]
                elsif transaction.match(/NEGATIVE_ADJUSTMENTS/i)
                  transaction_id = d[:epics_product_order_id]
                elsif transaction == 'RECEIPTS'
                  transaction_id = d[:epics_stock_details_id]
                elsif transaction == 'ISSUES'
                  transaction_id = d[:epics_product_order_id]
                end
      %>
      <tr class="tbody-data row_<%=color%>">
        <td><%=date.to_date.strftime("%d-%b-%Y")%></td>
        <td><%=invoice_number%></td>
        <td><%=d[:received_quantity]%></td>
        <td><%=d[:issued]%></td>
        <td><%=d[:losses]%></td>
        <td><%=d[:quantity_received]%></td>
        <td><%=d[:quantity_given_out]%></td>
        <td><%=current_quantity%></td>
        <td><%=remark%></td>
        <%if User.current.epics_user_role.name == "Administrator" && transaction == "ISSUES" %>
          <td style="text-align: center; vertical-align: middle;">
            <%= image_tag("close.png", :class => 'void-buttons', 
              :onclick =>"confirm(#{transaction_id},'#{d[:transaction]}')") %>
          </td>
         <% elsif User.current.epics_user_role.name == "Administrator" %>
            <td style="text-align: center; vertical-align: middle;">
              &nbsp;
            </td>
        <%end%>
      </tr>
      
          <%end
          end
        end
      end %>
      </tbody>
    </table>
  </div>
   <div id="shadow" class="opaqueLayer"> </div>
   <div id="question" class="confirmation" >
       Are you sure you want to void this transaction?
        <br><br>
     <button class='btn' id='yes'>Yes</button> <button class='btn' onmousedown="hide()">No</button>
   </div>
   </div>

  </body>
</html>

app/views/product/view.html.erb
<script>
  current_stock_id = ""
  current_reason = ""
  function voidNode(){

    jQuery.ajax({
      type: "POST",
      url: "/product/void",
      data: "product_id=<%=@product.id %>",
      success: function(){
        document.location.href="/"
      }

    });
  }

  function showPopup(node){
    current_stock_id = node.getAttribute('id')
    document.getElementsByClassName('select_reason')[0].style.display=''
    document.getElementById('cover').style.display=''
  }

  function hidePopups(){
    document.getElementsByClassName('select_reason')[0].style.display='none'
    document.getElementById('cover').style.display='none'
  }

  function selectReason(node){
    current_reason = node.getAttribute('reason');
    window.location="/stock_details/edit_current_quantity?stock_id=" + current_stock_id + '&reason=' + current_reason
    /*jQuery.ajax({
      type: "POST",
      url: "/stock_details/board_off_stock",
      data: "stock_id=" + current_stock_id + '&reason=' + current_reason,
      success: function(){
        elements = document.getElementsByTagName("tr")
        for(i=0; i<elements.length; i++){
           if (elements[i].getAttribute('stock_id')){
             if (elements[i].getAttribute('stock_id') == current_stock_id){
               elements[i].parentNode.removeChild(elements[i]);
               break;
             }
           }
        }
        current_stock_id = ""
        current_reason = ""
        hidePopups();
      }

    });*/
    
  }

  function editStock(stockId){
    window.location="/stock_details/edit_stock_details?stock_id=" + stockId
  }
</script>

<style type="text/css">
.product-table {
  width: 100%;
  text-align: left;
}

.product-table td {
  border-style: solid;
  border-width: 1px 0px 0px 0px;
}

.left-side {
  float: left;
  width: 75%;
  overflow: auto;
  height: 390px;
}

.right-side {
  float: right;
  width: 20%;
}


.menu-buttons {                                                               
    padding: 10px;                                                              
    float: right;                                                               
    width: 30%;                                                                 
    margin-right: 10px;                                                         
    border-style: solid;                                                        
    border-width: 0px 0px 0px 1px;                                              
  }                                                                             
                                                                                
  .menu-buttons a {                                                             
    width: 95%;                                                                 
  }                                                                             
                                                                                
  .buttons{
        border-bottom: 1px outset #EEEEEE;
        border-style: outset;
        border-top: 1px outset #EEEEEE;
        color: white;
        display: block;
        padding: 14px;
        text-align: center;
        text-decoration: none;
        box-shadow:inset 0px 1px 0px 0px #bbdaf7;
        background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #79bbff), color-stop(1, #378de5) );
        background:-moz-linear-gradient( center top, #79bbff 5%, #378de5 100% );
        filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#79bbff', endColorstr='#378de5');
        background-color:#79bbff;
        -moz-border-radius:42px;
        -webkit-border-radius:42px;
        -moz-box-shadow:inset 0px 1px 0px 0px #bbdaf7;
        -webkit-box-shadow:inset 0px 1px 0px 0px #bbdaf7;
        border-radius:42px;
        border:1px solid #84bbf3;
        border-bottom-color: rgba(0, 0, 0, 0.25);
        border-left-color-ltr-source: physical;
        border-left-color-rtl-source: physical;
        border-left-color-value: rgba(0, 0, 0, 0.1);
        border-right-color-ltr-source: physical;
        border-right-color-rtl-source: physical;
        border-right-color-value: rgba(0, 0, 0, 0.1);
        border-top-color: rgba(0, 0, 0, 0.1);
        font-size: 1.3em;
        font-weight:bold;                                                          
  }       

  .img{
    height: 60px;
   }
</style>


<h1><%=@product.product_code%>:&nbsp;<%=@product.name%></h1>
<p><%=@product.epics_product_type.name%></p>
<div class="product-container">

<% cost = @product.epics_item_cost %>
<b>&nbsp;Unit:</b>&nbsp;<%=@product.epics_product_units.name %>
<b>&nbsp;Unit price:</b>&nbsp;<%=cost.unit_price rescue nil %>
<b>&nbsp;Pack size:</b>&nbsp;<%=cost.pack_size rescue nil %>
<b>&nbsp;Billing charge:</b>&nbsp;<%=cost.billing_charge rescue nil %>
<hr />
<br />

<div class="left-side">
  <table class="product-table">
    <tr>
      <th style="width: 15%;">Expiry date</th>
      <th style="width: 20%; text-align: right;padding-right: 10px;">Received quantity</th>
      <th style="width: 20%; text-align: right;padding-right: 10px;">Current quantity</th>
      <th style="width: 25%;padding-left: 10px;">Location</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
    </tr>
    <%(@product.epics_stock_details || []).each do |stock|%>
      <tr stock_id="<%= stock.id %>">
        <td><%=stock.epics_stock_expiry_date.expiry_date.strftime('%B %Y') rescue 'N/A'%></td>
        <td style="text-align: right;padding-right: 10px;"><%=stock.received_quantity%></td>
        <td style="text-align: right;padding-right: 10px;"><%=stock.current_quantity%></td>
        <td style="padding-left: 10px;"><%=stock.epics_location.name%></td>
        <% if stock.current_quantity == stock.received_quantity %>
            <td style="width: 10%;"><%= image_tag("close.png",:id => stock.id, :class=>"img", :onclick=>"showPopup(this);") %></td>
            <td style="width: 10%;"><%= image_tag("pencil.png",:id => stock.id, :class=>"img", :onclick=>"editStock(this.id)") %></td>
        <% else %>
            <td style="width: 10%;"> &nbsp;</td>
            <td style="width: 10%;"> &nbsp;</td>
        <% end %>
      </tr>
    <%end%>
  </table>
</div>

<div class="right-side">
  <table class="button-table" style="width: 99%;">
    <tr>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td><%#= link_to "Stock card", {:action =>"stock_card",:id => @product.id}, :class => 'buttons' %></td>
    </tr>
    <tr>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td><%#= link_to "Set/Edit Cost", edit_cost_url(:id => @product.id), :class => 'buttons' %></td>
    </tr>
    <tr>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td><%#= link_to "Edit Item", edit_item_url(:id => @product.id), :class => 'buttons' %></td>
    </tr>
    <!--tr>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td><%#= link_to "Remove", "#", :class => 'buttons' ,:onclick=>"voidNode();"%></td>
    </tr>-->
  </table>
</div>
</div>

<div class="select_reason" style="display:none;">
  <div id="reasons">
    <table  width="100%" border=0.5 style = "border-radius:10px;">
      <tr>
        <th colspan="2">Select Reason</th>
      </tr>
      <tr>
        <td cospan="2"><a class="buttons" reason="expired" onclick="selectReason(this);"><span>Expired</span></a> </td>
      </tr>
      <tr>
        <td cospan="2"><hr/></td>
      </tr>
      <tr>
        <td colspan="2"><a class="buttons" reason="damaged" onclick="selectReason(this);"><span>Damaged</span></a> </td>
      </tr>
      <tr>
        <td><hr/></td>
      </tr>
      <tr>
        <td colspan="2"><a class="buttons" reason="missing" onclick="selectReason(this);"><span>Missing</span></a> </td>
      </tr>
      <tr>
        <td><hr/></td>
      </tr>
      <tr>
        <td colspan="2"><a class="buttons" reason="wrongly captured" onclick="selectReason(this);"><span>Wrongly captured</span></a> </td>
      </tr>
      <tr>
        <td colspan="2"><%= image_tag("close.png",:id=>"close", :onclick=>"hidePopups();") %></td>
      </tr>
    </table>
  </div>
</div>
<div id="cover" style="display: none">

</div>
<style>
  #close{
    position: absolute;
    height: 60px;
    left: 45%;
    padding-top: 10px;
  }
  #reasons table{
      background-color:#FEF6E4;
      color: black;
      font-size: 18pt;
      font-weight: bold;
      left: 30%;
      line-height: 35px;
      position: absolute;
      top: 152px;
      width: 500px;
      border: 1px solid black;
      z-index: 999;
      padding: 0px 20px 70px 20px;
      -moz-user-select:none;
    }
   #cover{
      position: absolute;
      background-color: black;
      width: 100%;
      height: 100%;
      left: 0%;
      top: 0%;
      z-index: 990;
      opacity: 0.5;
    }

</style>